#!/bin/sh
#
# Post-update hook to prepare for deployment
#

# Update the working tree after changes have been pushed here
cd ..
env -i git checkout -f

# Laravel maintenance down
php artisan down

# Update dependencies

if [ -f composer.json ]; then
    ## Install or update packages specified in the lock file
    composer install
fi

if [ -f package.json ]; then
    ## Install or update node packages
    npm install
fi

if [ -f bower.json ]; then
    ## install or update bower packages
    bower install
fi

# Build assets & cie

if [ -f gulpfile.json ]; then
    # gulp deploy --production
fi

if [ -f Gruntfile ]; then
    # grunt
fi

# Generate optimized class loader
php artisan optimize

# Cache config files
php artisan config:cache

# Laravel maintenance up
php artisan up


