#!/bin/sh
#
# Post-update hook to ensure dependencies are up to date
#

# Update dependencies
composer update
# npm update
# bower update

# Build assets & cie
# gulp deploy --production
# grunt deploy --production
